### ISSUE TITLE
55-micro-frontends-in-action-end; branch code doesn't work 

### ISSUE THREAD

**Issue by sunilkumardasdev** [vp-online-courses/webpack-tutorial#13]
[http://localhost:9000/kiwi-page](http://localhost:9000/kiwi-page) and [http://localhost:9000/hello-world-page](http://localhost:9000/hello-world-page) pages doesn't load.

![Screenshot (3)](https://user-images.githubusercontent.com/50082751/203127424-e9b0fc9f-95cb-4c3c-a1ed-fefed47c2e80.png)

**Comment by vp-online-courses** [comment]
Hi DDASSS,

First of all, apologies for the late reply.
I've checked the branch named "55-micro-frontends-in-action-end" with Node.js v19.7.0 and npm v9.5.0, and everything seems to work in that branch. When checking, I was using the latest versions of Webpack (v5.88.2) and webpack-cli (v5.1.4) available at the moment.

Here are the screenshots attached:

<img width="1792" alt="Screenshot 2023-07-20 at 18 48 33" src="https://github.com/vp-online-courses/webpack-tutorial/assets/41524972/ea2bcff1-1861-48c5-aa16-dd09238df284">

<img width="1792" alt="Screenshot 2023-07-20 at 18 53 46" src="https://github.com/vp-online-courses/webpack-tutorial/assets/41524972/d3379733-4b63-44a8-a4ab-fb2dfaa4f225">

Probably there was another issue related to your source code or configuration, but unfortunately I can't figure it out based on your posted screenshots.

Best regards,
Viktor

**Comment by vp-online-courses** [comment]
Closing this since the branch code is working properly as per comment above.
